name: TestCI

on:
  pull_request:
    branches:
      - main
      - stage
  push:
    branches:
      - main
      - stage
env:
  SEMANTIC_RELEASE_PACKAGE: roux-test

jobs:
  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: npm ci
      - name: Semantic Release
        id: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
