name: merge-queue-test

on:
  pull_request:
  merge_group:

env:
  SEMANTIC_RELEASE_PACKAGE: roux-test

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 1
