name: merge-queue test

on:
  merge_group:
    types: [checks_requested]

env:
  SEMANTIC_RELEASE_PACKAGE: roux-test

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Dependencies
        run: npm ci
