name: merge-queue-test

on:
  merge_group:
    branches:
      - main
    types:
      - checks_requested

env:
  SEMANTIC_RELEASE_PACKAGE: roux-test

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 1
