name: merge-queue-test

on:
  pull_request:
  merge_group:
    types: [checks_requested]


env:
  SEMANTIC_RELEASE_PACKAGE: roux-test

jobs:
  publish:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 1
